<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>DV_TableauProject2</title>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
   white-space: pre-wrap;
}

pre code {
   display: block; padding: 0.5em;
}

code.r, code.cpp {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: rgb(88, 72, 246)
   }

   pre .number {
     color: rgb(0, 0, 205);
   }

   pre .comment {
     color: rgb(76, 136, 107);
   }

   pre .keyword {
     color: rgb(0, 0, 255);
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: rgb(3, 106, 7);
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>




</head>

<body>
<h2>DV_TableauProject2</h2>

<h1></h1>

<h4>Group member: Anna Mengjie Yu (my3852),  Duy Vu (dhv242),  Syed Naqvi (san724)</h4>

<p>In this project, we use the same plastid genome data we used in DV_RProject3. </p>

<p>The length of a gene determines the number of amino acid this gene encodes. The longer the gene, the more likely or more important function it might have. In the plastid genomes, the gene can be in either forward or reverse direction. We partition the genes by direction, and try to discover the length variation of those genes.</p>

<p>We produced the same crosstabs in both R and Tableau.</p>

<hr/>

<p>Load packages</p>

<pre><code class="r">source(&quot;../01 SQL Crosstabs/project5_loadPackage.R&quot;, echo = TRUE)
</code></pre>

<pre><code>## 
## &gt; require(&quot;ggplot2&quot;)
</code></pre>

<pre><code>## Loading required package: ggplot2
</code></pre>

<pre><code>## 
## &gt; require(&quot;gplots&quot;)
</code></pre>

<pre><code>## Loading required package: gplots
## 
## Attaching package: &#39;gplots&#39;
## 
## The following object is masked from &#39;package:stats&#39;:
## 
##     lowess
</code></pre>

<pre><code>## 
## &gt; require(&quot;grid&quot;)
</code></pre>

<pre><code>## Loading required package: grid
</code></pre>

<pre><code>## 
## &gt; require(&quot;RCurl&quot;)
</code></pre>

<pre><code>## Loading required package: RCurl
## Loading required package: bitops
</code></pre>

<pre><code>## 
## &gt; require(&quot;reshape2&quot;)
</code></pre>

<pre><code>## Loading required package: reshape2
</code></pre>

<pre><code>## 
## &gt; require(&quot;tidyr&quot;)
</code></pre>

<pre><code>## Loading required package: tidyr
</code></pre>

<pre><code>## 
## &gt; require(&quot;dplyr&quot;)
</code></pre>

<pre><code>## Loading required package: dplyr
## 
## Attaching package: &#39;dplyr&#39;
## 
## The following object is masked from &#39;package:stats&#39;:
## 
##     filter
## 
## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union
</code></pre>

<pre><code>## 
## &gt; require(&quot;jsonlite&quot;)
</code></pre>

<pre><code>## Loading required package: jsonlite
## 
## Attaching package: &#39;jsonlite&#39;
## 
## The following object is masked from &#39;package:utils&#39;:
## 
##     View
</code></pre>

<hr/>

<p><strong>Table 1: Rank</strong></p>

<hr/>

<p>In this table, we created a new column named LEN_RANK, we partition the genes by DIRECTION(forward and reverse). </p>

<p>We can see that in forward direction, rpoC2 and rpoB genes are ranked top 1 and top 2, respectively, in terms of length. rpo genes are ribosome proterin genes are important gens in charge of protein synthesis.</p>

<p>In ther reverse direction, rnl rRNA is the longest. rRNA is ribosome RNA responsible for transcription and translation. It plays a critical part in protein synthesis.</p>

<pre><code class="r">source(&quot;../01 SQL Crosstabs/ocean_rank.R&quot;, echo = TRUE)
</code></pre>

<pre><code>## 
## &gt; ocean_rank &lt;- data.frame(fromJSON(getURL(URLencode(gsub(&quot;\n&quot;, 
## +     &quot; &quot;, &quot;129.152.144.84:5001/rest/native/?query=\&quot;select direction, length, name,  .... [TRUNCATED] 
## 
## &gt; ocean_rank
##     DIRECTION LENGTH        NAME LEN_RANK
## 1     forward   4362   rpoC2 CDS        1
## 2     forward   4095    rpoB CDS        2
## 3     forward   2886    rnl rRNA        3
## 4     forward   2799    clpC CDS        4
## 5     forward   2628    secA CDS        5
## 6     forward   2259    psaA CDS        6
## 7     forward   2202    psaB CDS        7
## 8     forward   2139   rpoC1 CDS        8
## 9     forward   1494   ycf46 CDS        9
## 10    forward   1479    rns rRNA       10
## 11    forward   1473    rbcL CDS       11
## 12    forward   1407   ycf90 CDS       12
## 13    forward   1368    dnaB CDS       13
## 14    forward   1266    ccs1 CDS       14
## 15    forward   1251    secY CDS       15
## 16    forward   1230    tufA CDS       16
## 17    forward   1083    psbA CDS       17
## 18    forward    999    rpoA CDS       18
## 19    forward    987   ycf89 CDS       19
## 20    forward    978    ccsA CDS       20
## 21    forward    963   ycf39 CDS       21
## 22    forward    924    rbcR CDS       22
## 23    forward    864    cbbX CDS       23
## 24    forward    828    rpl2 CDS       24
## 25    forward    804    thiG CDS       25
## 26    forward    717    rpl5 CDS       26
## 27    forward    699    rps2 CDS       27
## 28    forward    648    petB CDS       28
## 29    forward    645    rpl4 CDS       29
## 30    forward    645    rps3 CDS       29
## 31    forward    624    rpl3 CDS       31
## 32    forward    618    rps4 CDS       32
## 33    forward    558    psaF CDS       33
## 34    forward    537    rpl6 CDS       34
## 35    forward    531    rps5 CDS       35
## 36    forward    483    petD CDS       36
## 37    forward    471    rps7 CDS       37
## 38    forward    447    psaL CDS       38
## 39    forward    420    psaD CDS       39
## 40    forward    420    rbcS CDS       39
## 41    forward    417   rpl13 CDS       41
## 42    forward    411   rpl16 CDS       42
## 43    forward    408   rpl18 CDS       43
## 44    forward    405   ycf35 CDS       44
## 45    forward    405    rps9 CDS       44
## 46    forward    399    rps8 CDS       46
## 47    forward    393   rps11 CDS       47
## 48    forward    384   ycf88 CDS       48
## 49    forward    375   rps12 CDS       49
## 50    forward    372   rps13 CDS       50
## 51    forward    366   rpl14 CDS       51
## 52    forward    348   rpl22 CDS       52
## 53    forward    345   psb28 CDS       53
## 54    forward    324   rps10 CDS       54
## 55    forward    318   rpl21 CDS       55
## 56    forward    315   ycf41 CDS       56
## 57    forward    312    rps6 CDS       57
## 58    forward    309   rps20 CDS       58
## 59    forward    279   rps19 CDS       59
## 60    forward    279   rpl23 CDS       59
## 61    forward    255   rps17 CDS       61
## 62    forward    252   rps16 CDS       62
## 63    forward    252   rpl27 CDS       62
## 64    forward    246    psaC CDS       64
## 65    forward    234   rpl24 CDS       65
## 66    forward    219   rpl31 CDS       66
## 67    forward    210    secG CDS       67
## 68    forward    177   rpl29 CDS       68
## 69    forward    165   rpl32 CDS       69
## 70    forward    147   rpl34 CDS       70
## 71    forward    132    psbN CDS       71
## 72    forward    129    petM CDS       72
## 73    forward    126   rrn5 rRNA       73
## 74    forward    126    psaJ CDS       73
## 75    forward    117    psbI CDS       75
## 76    forward    114   rpl36 CDS       76
## 77    forward    111    psaI CDS       77
## 78    forward    111    psbY CDS       77
## 79    forward    100   ffs ncRNA       79
## 80    forward     90    petN CDS       80
## 81    forward     88 trnS-1 tRNA       81
## 82    forward     87 trnS-2 tRNA       82
## 83    forward     87 trnL-2 tRNA       82
## 84    forward     82 trnL-1 tRNA       84
## 85    forward     82   trnY tRNA       84
## 86    forward     74   trnD tRNA       86
## 87    forward     74  trnfM tRNA       86
## 88    forward     74   trnI tRNA       86
## 89    forward     74 trnR-3 tRNA       86
## 90    forward     74   trnP tRNA       86
## 91    forward     73 trnM-1 tRNA       91
## 92    forward     73        trnA       91
## 93    forward     73   trnH tRNA       91
## 94    forward     73 trnR-2 tRNA       91
## 95    forward     72   trnQ tRNA       95
## 96    forward     72   trnK tRNA       95
## 97    forward     72   trnV tRNA       95
## 98    forward     72   trnT tRNA       95
## 99    forward     72   trnN tRNA       95
## 100   forward     71   trnC tRNA      100
## 101   reverse   2886    rnl rRNA        1
## 102   reverse   2799    clpC CDS        2
## 103   reverse   2628    secA CDS        3
## 104   reverse   1929    ftsH CDS        4
## 105   reverse   1824    dnaK CDS        5
## 106   reverse   1593   groEL CDS        6
## 107   reverse   1530    psbB CDS        7
## 108   reverse   1512    atpA CDS        8
## 109   reverse   1494   ycf46 CDS        9
## 110   reverse   1479    rns rRNA       10
## 111   reverse   1458    sufB CDS       11
## 112   reverse   1425    atpB CDS       12
## 113   reverse   1416    psbC CDS       13
## 114   reverse   1359   ycf45 CDS       14
## 115   reverse   1266    ccs1 CDS       15
## 116   reverse   1083    psbA CDS       16
## 117   reverse   1059    chlI CDS       17
## 118   reverse   1056    psbD CDS       18
## 119   reverse    987   ycf89 CDS       19
## 120   reverse    978    ccsA CDS       20
## 121   reverse    945    petA CDS       21
## 122   reverse    924    rbcR CDS       22
## 123   reverse    756    sufC CDS       23
## 124   reverse    741    tatC CDS       24
## 125   reverse    729    atpI CDS       25
## 126   reverse    693    rpl1 CDS       26
## 127   reverse    636   ycf42 CDS       27
## 128   reverse    564    atpD CDS       28
## 129   reverse    555    ycf3 CDS       29
## 130   reverse    546    ycf4 CDS       30
## 131   reverse    540    atpF CDS       31
## 132   reverse    492    psbV CDS       32
## 133   reverse    471    atpG CDS       33
## 134   reverse    426   rpl11 CDS       34
## 135   reverse    423  orf127 CDS       35
## 136   reverse    405   ycf35 CDS       36
## 137   reverse    402    atpE CDS       37
## 138   reverse    387   rpl12 CDS       38
## 139   reverse    363   rpl19 CDS       39
## 140   reverse    360   rpl20 CDS       40
## 141   reverse    334  ssra tmRNA       41
## 142   reverse    318   rpl21 CDS       42
## 143   reverse    312   ycf66 CDS       43
## 144   reverse    303   rps14 CDS       44
## 145   reverse    255    psbE CDS       45
## 146   reverse    252   rpl27 CDS       46
## 147   reverse    249    atpH CDS       47
## 148   reverse    246    psaC CDS       48
## 149   reverse    219   rps18 CDS       49
## 150   reverse    213    thiS CDS       50
## 151   reverse    201    psbH CDS       51
## 152   reverse    198    psaE CDS       52
## 153   reverse    195   rpl35 CDS       53
## 154   reverse    195   ycf33 CDS       53
## 155   reverse    195   rpl33 CDS       53
## 156   reverse    186    psbZ CDS       56
## 157   reverse    165   rpl32 CDS       57
## 158   reverse    147   rpl34 CDS       58
## 159   reverse    135    psbK CDS       59
## 160   reverse    132    psbF CDS       60
## 161   reverse    126   rrn5 rRNA       61
## 162   reverse    120    psbJ CDS       62
## 163   reverse    117    psbL CDS       63
## 164   reverse    117    psbX CDS       63
## 165   reverse    114    petG CDS       65
## 166   reverse    111    psbY CDS       66
## 167   reverse    105   ycf12 CDS       67
## 168   reverse     99    psbT CDS       68
## 169   reverse     96    petL CDS       69
## 170   reverse     93    psaM CDS       70
## 171   reverse     87 trnL-2 tRNA       71
## 172   reverse     85 trnM-2 tRNA       72
## 173   reverse     82 trnL-1 tRNA       73
## 174   reverse     75  flrn ncRNA       74
## 175   reverse     74   trnI tRNA       75
## 176   reverse     74   trnP tRNA       75
## 177   reverse     73   trnF tRNA       77
## 178   reverse     73 trnR-1 tRNA       77
## 179   reverse     73   trnE tRNA       77
## 180   reverse     73   trnA tRNA       77
## 181   reverse     73   trnW tRNA       77
## 182   reverse     72 trnG-2 tRNA       82
## 183   reverse     72   trnC tRNA       82
## 184   reverse     71   trnC tRNA       84
## 185   reverse     71 trnG-1 tRNA       84
</code></pre>

<hr/>

<p><strong>Table 2: Max and Difference</strong></p>

<hr/>

<p>In Table 2, we created two new columns. One named Max_LEN showing the maximum gene length in each gene direction category. The second column LenDiff showing the difference of gene length compared to the maximum gene length in each directory category.</p>

<p>From this table, we can see that the gene length in forward direction varies much more (maxDiff 4291) than gene length in reverse direction(maxDiff 2815).</p>

<pre><code class="r">source(&quot;../01 SQL Crosstabs/ocean_diff.R&quot;, echo = TRUE)
</code></pre>

<pre><code>## 
## &gt; ocean_diff &lt;- data.frame(fromJSON(getURL(URLencode(gsub(&quot;\n&quot;, 
## +     &quot; &quot;, &quot;129.152.144.84:5001/rest/native/?query=\&quot;select direction,length, name, l .... [TRUNCATED] 
## 
## &gt; ocean_diff
##     DIRECTION LENGTH        NAME MAX_LEN LEN_DIFF
## 1     forward   4362   rpoC2 CDS    4362        0
## 2     forward   4095    rpoB CDS    4362      267
## 3     forward   2886    rnl rRNA    4362     1476
## 4     forward   2799    clpC CDS    4362     1563
## 5     forward   2628    secA CDS    4362     1734
## 6     forward   2259    psaA CDS    4362     2103
## 7     forward   2202    psaB CDS    4362     2160
## 8     forward   2139   rpoC1 CDS    4362     2223
## 9     forward   1494   ycf46 CDS    4362     2868
## 10    forward   1479    rns rRNA    4362     2883
## 11    forward   1473    rbcL CDS    4362     2889
## 12    forward   1407   ycf90 CDS    4362     2955
## 13    forward   1368    dnaB CDS    4362     2994
## 14    forward   1266    ccs1 CDS    4362     3096
## 15    forward   1251    secY CDS    4362     3111
## 16    forward   1230    tufA CDS    4362     3132
## 17    forward   1083    psbA CDS    4362     3279
## 18    forward    999    rpoA CDS    4362     3363
## 19    forward    987   ycf89 CDS    4362     3375
## 20    forward    978    ccsA CDS    4362     3384
## 21    forward    963   ycf39 CDS    4362     3399
## 22    forward    924    rbcR CDS    4362     3438
## 23    forward    864    cbbX CDS    4362     3498
## 24    forward    828    rpl2 CDS    4362     3534
## 25    forward    804    thiG CDS    4362     3558
## 26    forward    717    rpl5 CDS    4362     3645
## 27    forward    699    rps2 CDS    4362     3663
## 28    forward    648    petB CDS    4362     3714
## 29    forward    645    rpl4 CDS    4362     3717
## 30    forward    645    rps3 CDS    4362     3717
## 31    forward    624    rpl3 CDS    4362     3738
## 32    forward    618    rps4 CDS    4362     3744
## 33    forward    558    psaF CDS    4362     3804
## 34    forward    537    rpl6 CDS    4362     3825
## 35    forward    531    rps5 CDS    4362     3831
## 36    forward    483    petD CDS    4362     3879
## 37    forward    471    rps7 CDS    4362     3891
## 38    forward    447    psaL CDS    4362     3915
## 39    forward    420    rbcS CDS    4362     3942
## 40    forward    420    psaD CDS    4362     3942
## 41    forward    417   rpl13 CDS    4362     3945
## 42    forward    411   rpl16 CDS    4362     3951
## 43    forward    408   rpl18 CDS    4362     3954
## 44    forward    405    rps9 CDS    4362     3957
## 45    forward    405   ycf35 CDS    4362     3957
## 46    forward    399    rps8 CDS    4362     3963
## 47    forward    393   rps11 CDS    4362     3969
## 48    forward    384   ycf88 CDS    4362     3978
## 49    forward    375   rps12 CDS    4362     3987
## 50    forward    372   rps13 CDS    4362     3990
## 51    forward    366   rpl14 CDS    4362     3996
## 52    forward    348   rpl22 CDS    4362     4014
## 53    forward    345   psb28 CDS    4362     4017
## 54    forward    324   rps10 CDS    4362     4038
## 55    forward    318   rpl21 CDS    4362     4044
## 56    forward    315   ycf41 CDS    4362     4047
## 57    forward    312    rps6 CDS    4362     4050
## 58    forward    309   rps20 CDS    4362     4053
## 59    forward    279   rpl23 CDS    4362     4083
## 60    forward    279   rps19 CDS    4362     4083
## 61    forward    255   rps17 CDS    4362     4107
## 62    forward    252   rpl27 CDS    4362     4110
## 63    forward    252   rps16 CDS    4362     4110
## 64    forward    246    psaC CDS    4362     4116
## 65    forward    234   rpl24 CDS    4362     4128
## 66    forward    219   rpl31 CDS    4362     4143
## 67    forward    210    secG CDS    4362     4152
## 68    forward    177   rpl29 CDS    4362     4185
## 69    forward    165   rpl32 CDS    4362     4197
## 70    forward    147   rpl34 CDS    4362     4215
## 71    forward    132    psbN CDS    4362     4230
## 72    forward    129    petM CDS    4362     4233
## 73    forward    126   rrn5 rRNA    4362     4236
## 74    forward    126    psaJ CDS    4362     4236
## 75    forward    117    psbI CDS    4362     4245
## 76    forward    114   rpl36 CDS    4362     4248
## 77    forward    111    psaI CDS    4362     4251
## 78    forward    111    psbY CDS    4362     4251
## 79    forward    100   ffs ncRNA    4362     4262
## 80    forward     90    petN CDS    4362     4272
## 81    forward     88 trnS-1 tRNA    4362     4274
## 82    forward     87 trnL-2 tRNA    4362     4275
## 83    forward     87 trnS-2 tRNA    4362     4275
## 84    forward     82 trnL-1 tRNA    4362     4280
## 85    forward     82   trnY tRNA    4362     4280
## 86    forward     74   trnD tRNA    4362     4288
## 87    forward     74   trnI tRNA    4362     4288
## 88    forward     74   trnP tRNA    4362     4288
## 89    forward     74 trnR-3 tRNA    4362     4288
## 90    forward     74  trnfM tRNA    4362     4288
## 91    forward     73   trnH tRNA    4362     4289
## 92    forward     73        trnA    4362     4289
## 93    forward     73 trnM-1 tRNA    4362     4289
## 94    forward     73 trnR-2 tRNA    4362     4289
## 95    forward     72   trnT tRNA    4362     4290
## 96    forward     72   trnK tRNA    4362     4290
## 97    forward     72   trnV tRNA    4362     4290
## 98    forward     72   trnN tRNA    4362     4290
## 99    forward     72   trnQ tRNA    4362     4290
## 100   forward     71   trnC tRNA    4362     4291
## 101   reverse   2886    rnl rRNA    2886        0
## 102   reverse   2799    clpC CDS    2886       87
## 103   reverse   2628    secA CDS    2886      258
## 104   reverse   1929    ftsH CDS    2886      957
## 105   reverse   1824    dnaK CDS    2886     1062
## 106   reverse   1593   groEL CDS    2886     1293
## 107   reverse   1530    psbB CDS    2886     1356
## 108   reverse   1512    atpA CDS    2886     1374
## 109   reverse   1494   ycf46 CDS    2886     1392
## 110   reverse   1479    rns rRNA    2886     1407
## 111   reverse   1458    sufB CDS    2886     1428
## 112   reverse   1425    atpB CDS    2886     1461
## 113   reverse   1416    psbC CDS    2886     1470
## 114   reverse   1359   ycf45 CDS    2886     1527
## 115   reverse   1266    ccs1 CDS    2886     1620
## 116   reverse   1083    psbA CDS    2886     1803
## 117   reverse   1059    chlI CDS    2886     1827
## 118   reverse   1056    psbD CDS    2886     1830
## 119   reverse    987   ycf89 CDS    2886     1899
## 120   reverse    978    ccsA CDS    2886     1908
## 121   reverse    945    petA CDS    2886     1941
## 122   reverse    924    rbcR CDS    2886     1962
## 123   reverse    756    sufC CDS    2886     2130
## 124   reverse    741    tatC CDS    2886     2145
## 125   reverse    729    atpI CDS    2886     2157
## 126   reverse    693    rpl1 CDS    2886     2193
## 127   reverse    636   ycf42 CDS    2886     2250
## 128   reverse    564    atpD CDS    2886     2322
## 129   reverse    555    ycf3 CDS    2886     2331
## 130   reverse    546    ycf4 CDS    2886     2340
## 131   reverse    540    atpF CDS    2886     2346
## 132   reverse    492    psbV CDS    2886     2394
## 133   reverse    471    atpG CDS    2886     2415
## 134   reverse    426   rpl11 CDS    2886     2460
## 135   reverse    423  orf127 CDS    2886     2463
## 136   reverse    405   ycf35 CDS    2886     2481
## 137   reverse    402    atpE CDS    2886     2484
## 138   reverse    387   rpl12 CDS    2886     2499
## 139   reverse    363   rpl19 CDS    2886     2523
## 140   reverse    360   rpl20 CDS    2886     2526
## 141   reverse    334  ssra tmRNA    2886     2552
## 142   reverse    318   rpl21 CDS    2886     2568
## 143   reverse    312   ycf66 CDS    2886     2574
## 144   reverse    303   rps14 CDS    2886     2583
## 145   reverse    255    psbE CDS    2886     2631
## 146   reverse    252   rpl27 CDS    2886     2634
## 147   reverse    249    atpH CDS    2886     2637
## 148   reverse    246    psaC CDS    2886     2640
## 149   reverse    219   rps18 CDS    2886     2667
## 150   reverse    213    thiS CDS    2886     2673
## 151   reverse    201    psbH CDS    2886     2685
## 152   reverse    198    psaE CDS    2886     2688
## 153   reverse    195   rpl35 CDS    2886     2691
## 154   reverse    195   rpl33 CDS    2886     2691
## 155   reverse    195   ycf33 CDS    2886     2691
## 156   reverse    186    psbZ CDS    2886     2700
## 157   reverse    165   rpl32 CDS    2886     2721
## 158   reverse    147   rpl34 CDS    2886     2739
## 159   reverse    135    psbK CDS    2886     2751
## 160   reverse    132    psbF CDS    2886     2754
## 161   reverse    126   rrn5 rRNA    2886     2760
## 162   reverse    120    psbJ CDS    2886     2766
## 163   reverse    117    psbX CDS    2886     2769
## 164   reverse    117    psbL CDS    2886     2769
## 165   reverse    114    petG CDS    2886     2772
## 166   reverse    111    psbY CDS    2886     2775
## 167   reverse    105   ycf12 CDS    2886     2781
## 168   reverse     99    psbT CDS    2886     2787
## 169   reverse     96    petL CDS    2886     2790
## 170   reverse     93    psaM CDS    2886     2793
## 171   reverse     87 trnL-2 tRNA    2886     2799
## 172   reverse     85 trnM-2 tRNA    2886     2801
## 173   reverse     82 trnL-1 tRNA    2886     2804
## 174   reverse     75  flrn ncRNA    2886     2811
## 175   reverse     74   trnP tRNA    2886     2812
## 176   reverse     74   trnI tRNA    2886     2812
## 177   reverse     73   trnW tRNA    2886     2813
## 178   reverse     73 trnR-1 tRNA    2886     2813
## 179   reverse     73   trnA tRNA    2886     2813
## 180   reverse     73   trnE tRNA    2886     2813
## 181   reverse     73   trnF tRNA    2886     2813
## 182   reverse     72   trnC tRNA    2886     2814
## 183   reverse     72 trnG-2 tRNA    2886     2814
## 184   reverse     71   trnC tRNA    2886     2815
## 185   reverse     71 trnG-1 tRNA    2886     2815
</code></pre>

<hr/>

<p><strong>Table 3: Nth Rank</strong></p>

<hr/>

<p>In Table 3, we created a new column named NTH_LENGTH, we showed the 5th longest gene length in each direction category. We can see that in the forward direction category, the 5th longest gene length is 2628. While in the reverse direction category, the 5th longest gene length is 1824.</p>

<pre><code class="r">source(&quot;../01 SQL Crosstabs/ocean_Nth.R&quot;, echo = TRUE)
</code></pre>

<pre><code>## 
## &gt; ocean_Nth &lt;- data.frame(fromJSON(getURL(URLencode(gsub(&quot;\n&quot;, 
## +     &quot; &quot;, &quot;129.152.144.84:5001/rest/native/?query=\&quot;select direction,length, name, nt .... [TRUNCATED] 
## 
## &gt; ocean_Nth
##     DIRECTION LENGTH        NAME NTH_LENGTH
## 1     forward   4362   rpoC2 CDS       2628
## 2     forward   4095    rpoB CDS       2628
## 3     forward   2886    rnl rRNA       2628
## 4     forward   2799    clpC CDS       2628
## 5     forward   2628    secA CDS       2628
## 6     forward   2259    psaA CDS       2628
## 7     forward   2202    psaB CDS       2628
## 8     forward   2139   rpoC1 CDS       2628
## 9     forward   1494   ycf46 CDS       2628
## 10    forward   1479    rns rRNA       2628
## 11    forward   1473    rbcL CDS       2628
## 12    forward   1407   ycf90 CDS       2628
## 13    forward   1368    dnaB CDS       2628
## 14    forward   1266    ccs1 CDS       2628
## 15    forward   1251    secY CDS       2628
## 16    forward   1230    tufA CDS       2628
## 17    forward   1083    psbA CDS       2628
## 18    forward    999    rpoA CDS       2628
## 19    forward    987   ycf89 CDS       2628
## 20    forward    978    ccsA CDS       2628
## 21    forward    963   ycf39 CDS       2628
## 22    forward    924    rbcR CDS       2628
## 23    forward    864    cbbX CDS       2628
## 24    forward    828    rpl2 CDS       2628
## 25    forward    804    thiG CDS       2628
## 26    forward    717    rpl5 CDS       2628
## 27    forward    699    rps2 CDS       2628
## 28    forward    648    petB CDS       2628
## 29    forward    645    rpl4 CDS       2628
## 30    forward    645    rps3 CDS       2628
## 31    forward    624    rpl3 CDS       2628
## 32    forward    618    rps4 CDS       2628
## 33    forward    558    psaF CDS       2628
## 34    forward    537    rpl6 CDS       2628
## 35    forward    531    rps5 CDS       2628
## 36    forward    483    petD CDS       2628
## 37    forward    471    rps7 CDS       2628
## 38    forward    447    psaL CDS       2628
## 39    forward    420    psaD CDS       2628
## 40    forward    420    rbcS CDS       2628
## 41    forward    417   rpl13 CDS       2628
## 42    forward    411   rpl16 CDS       2628
## 43    forward    408   rpl18 CDS       2628
## 44    forward    405   ycf35 CDS       2628
## 45    forward    405    rps9 CDS       2628
## 46    forward    399    rps8 CDS       2628
## 47    forward    393   rps11 CDS       2628
## 48    forward    384   ycf88 CDS       2628
## 49    forward    375   rps12 CDS       2628
## 50    forward    372   rps13 CDS       2628
## 51    forward    366   rpl14 CDS       2628
## 52    forward    348   rpl22 CDS       2628
## 53    forward    345   psb28 CDS       2628
## 54    forward    324   rps10 CDS       2628
## 55    forward    318   rpl21 CDS       2628
## 56    forward    315   ycf41 CDS       2628
## 57    forward    312    rps6 CDS       2628
## 58    forward    309   rps20 CDS       2628
## 59    forward    279   rps19 CDS       2628
## 60    forward    279   rpl23 CDS       2628
## 61    forward    255   rps17 CDS       2628
## 62    forward    252   rps16 CDS       2628
## 63    forward    252   rpl27 CDS       2628
## 64    forward    246    psaC CDS       2628
## 65    forward    234   rpl24 CDS       2628
## 66    forward    219   rpl31 CDS       2628
## 67    forward    210    secG CDS       2628
## 68    forward    177   rpl29 CDS       2628
## 69    forward    165   rpl32 CDS       2628
## 70    forward    147   rpl34 CDS       2628
## 71    forward    132    psbN CDS       2628
## 72    forward    129    petM CDS       2628
## 73    forward    126   rrn5 rRNA       2628
## 74    forward    126    psaJ CDS       2628
## 75    forward    117    psbI CDS       2628
## 76    forward    114   rpl36 CDS       2628
## 77    forward    111    psaI CDS       2628
## 78    forward    111    psbY CDS       2628
## 79    forward    100   ffs ncRNA       2628
## 80    forward     90    petN CDS       2628
## 81    forward     88 trnS-1 tRNA       2628
## 82    forward     87 trnS-2 tRNA       2628
## 83    forward     87 trnL-2 tRNA       2628
## 84    forward     82 trnL-1 tRNA       2628
## 85    forward     82   trnY tRNA       2628
## 86    forward     74   trnD tRNA       2628
## 87    forward     74  trnfM tRNA       2628
## 88    forward     74   trnI tRNA       2628
## 89    forward     74 trnR-3 tRNA       2628
## 90    forward     74   trnP tRNA       2628
## 91    forward     73 trnM-1 tRNA       2628
## 92    forward     73        trnA       2628
## 93    forward     73   trnH tRNA       2628
## 94    forward     73 trnR-2 tRNA       2628
## 95    forward     72   trnQ tRNA       2628
## 96    forward     72   trnK tRNA       2628
## 97    forward     72   trnV tRNA       2628
## 98    forward     72   trnT tRNA       2628
## 99    forward     72   trnN tRNA       2628
## 100   forward     71   trnC tRNA       2628
## 101   reverse   2886    rnl rRNA       1824
## 102   reverse   2799    clpC CDS       1824
## 103   reverse   2628    secA CDS       1824
## 104   reverse   1929    ftsH CDS       1824
## 105   reverse   1824    dnaK CDS       1824
## 106   reverse   1593   groEL CDS       1824
## 107   reverse   1530    psbB CDS       1824
## 108   reverse   1512    atpA CDS       1824
## 109   reverse   1494   ycf46 CDS       1824
## 110   reverse   1479    rns rRNA       1824
## 111   reverse   1458    sufB CDS       1824
## 112   reverse   1425    atpB CDS       1824
## 113   reverse   1416    psbC CDS       1824
## 114   reverse   1359   ycf45 CDS       1824
## 115   reverse   1266    ccs1 CDS       1824
## 116   reverse   1083    psbA CDS       1824
## 117   reverse   1059    chlI CDS       1824
## 118   reverse   1056    psbD CDS       1824
## 119   reverse    987   ycf89 CDS       1824
## 120   reverse    978    ccsA CDS       1824
## 121   reverse    945    petA CDS       1824
## 122   reverse    924    rbcR CDS       1824
## 123   reverse    756    sufC CDS       1824
## 124   reverse    741    tatC CDS       1824
## 125   reverse    729    atpI CDS       1824
## 126   reverse    693    rpl1 CDS       1824
## 127   reverse    636   ycf42 CDS       1824
## 128   reverse    564    atpD CDS       1824
## 129   reverse    555    ycf3 CDS       1824
## 130   reverse    546    ycf4 CDS       1824
## 131   reverse    540    atpF CDS       1824
## 132   reverse    492    psbV CDS       1824
## 133   reverse    471    atpG CDS       1824
## 134   reverse    426   rpl11 CDS       1824
## 135   reverse    423  orf127 CDS       1824
## 136   reverse    405   ycf35 CDS       1824
## 137   reverse    402    atpE CDS       1824
## 138   reverse    387   rpl12 CDS       1824
## 139   reverse    363   rpl19 CDS       1824
## 140   reverse    360   rpl20 CDS       1824
## 141   reverse    334  ssra tmRNA       1824
## 142   reverse    318   rpl21 CDS       1824
## 143   reverse    312   ycf66 CDS       1824
## 144   reverse    303   rps14 CDS       1824
## 145   reverse    255    psbE CDS       1824
## 146   reverse    252   rpl27 CDS       1824
## 147   reverse    249    atpH CDS       1824
## 148   reverse    246    psaC CDS       1824
## 149   reverse    219   rps18 CDS       1824
## 150   reverse    213    thiS CDS       1824
## 151   reverse    201    psbH CDS       1824
## 152   reverse    198    psaE CDS       1824
## 153   reverse    195   rpl35 CDS       1824
## 154   reverse    195   ycf33 CDS       1824
## 155   reverse    195   rpl33 CDS       1824
## 156   reverse    186    psbZ CDS       1824
## 157   reverse    165   rpl32 CDS       1824
## 158   reverse    147   rpl34 CDS       1824
## 159   reverse    135    psbK CDS       1824
## 160   reverse    132    psbF CDS       1824
## 161   reverse    126   rrn5 rRNA       1824
## 162   reverse    120    psbJ CDS       1824
## 163   reverse    117    psbL CDS       1824
## 164   reverse    117    psbX CDS       1824
## 165   reverse    114    petG CDS       1824
## 166   reverse    111    psbY CDS       1824
## 167   reverse    105   ycf12 CDS       1824
## 168   reverse     99    psbT CDS       1824
## 169   reverse     96    petL CDS       1824
## 170   reverse     93    psaM CDS       1824
## 171   reverse     87 trnL-2 tRNA       1824
## 172   reverse     85 trnM-2 tRNA       1824
## 173   reverse     82 trnL-1 tRNA       1824
## 174   reverse     75  flrn ncRNA       1824
## 175   reverse     74   trnI tRNA       1824
## 176   reverse     74   trnP tRNA       1824
## 177   reverse     73   trnF tRNA       1824
## 178   reverse     73 trnR-1 tRNA       1824
## 179   reverse     73   trnE tRNA       1824
## 180   reverse     73   trnA tRNA       1824
## 181   reverse     73   trnW tRNA       1824
## 182   reverse     72 trnG-2 tRNA       1824
## 183   reverse     72   trnC tRNA       1824
## 184   reverse     71   trnC tRNA       1824
## 185   reverse     71 trnG-1 tRNA       1824
</code></pre>

<hr/>

<p><strong>Table 4: Accumulation Distribution</strong></p>

<hr/>

<p>In this Table, we created a new column named CUME_DIST, which shows the accumulative distribution of each gene in each category. From this table, we can see tRNA (transfer RNA) takes most of the lower cumulative percentage in both forward direction category and reverse category.</p>

<pre><code class="r">source(&quot;../01 SQL Crosstabs/ocean_cume.R&quot;, echo = TRUE)
</code></pre>

<pre><code>## 
## &gt; ocean_cume &lt;- data.frame(fromJSON(getURL(URLencode(gsub(&quot;\n&quot;, 
## +     &quot; &quot;, &quot;129.152.144.84:5001/rest/native/?query=\&quot;select direction,length, name, c .... [TRUNCATED] 
## 
## &gt; ocean_cume
##     DIRECTION LENGTH        NAME  CUME_DIST
## 1     forward   4362   rpoC2 CDS 1.00000000
## 2     forward   4095    rpoB CDS 0.99000001
## 3     forward   2886    rnl rRNA 0.98000002
## 4     forward   2799    clpC CDS 0.97000003
## 5     forward   2628    secA CDS 0.95999998
## 6     forward   2259    psaA CDS 0.94999999
## 7     forward   2202    psaB CDS 0.94000000
## 8     forward   2139   rpoC1 CDS 0.93000001
## 9     forward   1494   ycf46 CDS 0.92000002
## 10    forward   1479    rns rRNA 0.91000003
## 11    forward   1473    rbcL CDS 0.89999998
## 12    forward   1407   ycf90 CDS 0.88999999
## 13    forward   1368    dnaB CDS 0.88000000
## 14    forward   1266    ccs1 CDS 0.87000000
## 15    forward   1251    secY CDS 0.86000001
## 16    forward   1230    tufA CDS 0.85000002
## 17    forward   1083    psbA CDS 0.83999997
## 18    forward    999    rpoA CDS 0.82999998
## 19    forward    987   ycf89 CDS 0.81999999
## 20    forward    978    ccsA CDS 0.81000000
## 21    forward    963   ycf39 CDS 0.80000001
## 22    forward    924    rbcR CDS 0.79000002
## 23    forward    864    cbbX CDS 0.77999997
## 24    forward    828    rpl2 CDS 0.76999998
## 25    forward    804    thiG CDS 0.75999999
## 26    forward    717    rpl5 CDS 0.75000000
## 27    forward    699    rps2 CDS 0.74000001
## 28    forward    648    petB CDS 0.73000002
## 29    forward    645    rps3 CDS 0.72000003
## 30    forward    645    rpl4 CDS 0.72000003
## 31    forward    624    rpl3 CDS 0.69999999
## 32    forward    618    rps4 CDS 0.69000000
## 33    forward    558    psaF CDS 0.68000001
## 34    forward    537    rpl6 CDS 0.67000002
## 35    forward    531    rps5 CDS 0.66000003
## 36    forward    483    petD CDS 0.64999998
## 37    forward    471    rps7 CDS 0.63999999
## 38    forward    447    psaL CDS 0.63000000
## 39    forward    420    rbcS CDS 0.62000000
## 40    forward    420    psaD CDS 0.62000000
## 41    forward    417   rpl13 CDS 0.60000002
## 42    forward    411   rpl16 CDS 0.58999997
## 43    forward    408   rpl18 CDS 0.57999998
## 44    forward    405   ycf35 CDS 0.56999999
## 45    forward    405    rps9 CDS 0.56999999
## 46    forward    399    rps8 CDS 0.55000001
## 47    forward    393   rps11 CDS 0.54000002
## 48    forward    384   ycf88 CDS 0.52999997
## 49    forward    375   rps12 CDS 0.51999998
## 50    forward    372   rps13 CDS 0.50999999
## 51    forward    366   rpl14 CDS 0.50000000
## 52    forward    348   rpl22 CDS 0.49000001
## 53    forward    345   psb28 CDS 0.47999999
## 54    forward    324   rps10 CDS 0.47000000
## 55    forward    318   rpl21 CDS 0.46000001
## 56    forward    315   ycf41 CDS 0.44999999
## 57    forward    312    rps6 CDS 0.44000000
## 58    forward    309   rps20 CDS 0.43000001
## 59    forward    279   rpl23 CDS 0.41999999
## 60    forward    279   rps19 CDS 0.41999999
## 61    forward    255   rps17 CDS 0.40000001
## 62    forward    252   rpl27 CDS 0.38999999
## 63    forward    252   rps16 CDS 0.38999999
## 64    forward    246    psaC CDS 0.37000000
## 65    forward    234   rpl24 CDS 0.36000001
## 66    forward    219   rpl31 CDS 0.34999999
## 67    forward    210    secG CDS 0.34000000
## 68    forward    177   rpl29 CDS 0.33000001
## 69    forward    165   rpl32 CDS 0.31999999
## 70    forward    147   rpl34 CDS 0.31000000
## 71    forward    132    psbN CDS 0.30000001
## 72    forward    129    petM CDS 0.28999999
## 73    forward    126   rrn5 rRNA 0.28000000
## 74    forward    126    psaJ CDS 0.28000000
## 75    forward    117    psbI CDS 0.25999999
## 76    forward    114   rpl36 CDS 0.25000000
## 77    forward    111    psaI CDS 0.23999999
## 78    forward    111    psbY CDS 0.23999999
## 79    forward    100   ffs ncRNA 0.22000000
## 80    forward     90    petN CDS 0.20999999
## 81    forward     88 trnS-1 tRNA 0.20000000
## 82    forward     87 trnL-2 tRNA 0.19000000
## 83    forward     87 trnS-2 tRNA 0.19000000
## 84    forward     82 trnL-1 tRNA 0.17000000
## 85    forward     82   trnY tRNA 0.17000000
## 86    forward     74   trnD tRNA 0.15000001
## 87    forward     74   trnI tRNA 0.15000001
## 88    forward     74   trnP tRNA 0.15000001
## 89    forward     74 trnR-3 tRNA 0.15000001
## 90    forward     74  trnfM tRNA 0.15000001
## 91    forward     73   trnH tRNA 0.10000000
## 92    forward     73        trnA 0.10000000
## 93    forward     73 trnM-1 tRNA 0.10000000
## 94    forward     73 trnR-2 tRNA 0.10000000
## 95    forward     72   trnT tRNA 0.06000000
## 96    forward     72   trnK tRNA 0.06000000
## 97    forward     72   trnV tRNA 0.06000000
## 98    forward     72   trnN tRNA 0.06000000
## 99    forward     72   trnQ tRNA 0.06000000
## 100   forward     71   trnC tRNA 0.01000000
## 101   reverse   2886    rnl rRNA 1.00000000
## 102   reverse   2799    clpC CDS 0.98823529
## 103   reverse   2628    secA CDS 0.97647059
## 104   reverse   1929    ftsH CDS 0.96470588
## 105   reverse   1824    dnaK CDS 0.95294118
## 106   reverse   1593   groEL CDS 0.94117647
## 107   reverse   1530    psbB CDS 0.92941177
## 108   reverse   1512    atpA CDS 0.91764706
## 109   reverse   1494   ycf46 CDS 0.90588236
## 110   reverse   1479    rns rRNA 0.89411765
## 111   reverse   1458    sufB CDS 0.88235295
## 112   reverse   1425    atpB CDS 0.87058824
## 113   reverse   1416    psbC CDS 0.85882354
## 114   reverse   1359   ycf45 CDS 0.84705883
## 115   reverse   1266    ccs1 CDS 0.83529413
## 116   reverse   1083    psbA CDS 0.82352942
## 117   reverse   1059    chlI CDS 0.81176472
## 118   reverse   1056    psbD CDS 0.80000001
## 119   reverse    987   ycf89 CDS 0.78823531
## 120   reverse    978    ccsA CDS 0.77647060
## 121   reverse    945    petA CDS 0.76470590
## 122   reverse    924    rbcR CDS 0.75294119
## 123   reverse    756    sufC CDS 0.74117649
## 124   reverse    741    tatC CDS 0.72941178
## 125   reverse    729    atpI CDS 0.71764708
## 126   reverse    693    rpl1 CDS 0.70588237
## 127   reverse    636   ycf42 CDS 0.69411767
## 128   reverse    564    atpD CDS 0.68235296
## 129   reverse    555    ycf3 CDS 0.67058825
## 130   reverse    546    ycf4 CDS 0.65882355
## 131   reverse    540    atpF CDS 0.64705884
## 132   reverse    492    psbV CDS 0.63529414
## 133   reverse    471    atpG CDS 0.62352943
## 134   reverse    426   rpl11 CDS 0.61176473
## 135   reverse    423  orf127 CDS 0.60000002
## 136   reverse    405   ycf35 CDS 0.58823532
## 137   reverse    402    atpE CDS 0.57647061
## 138   reverse    387   rpl12 CDS 0.56470591
## 139   reverse    363   rpl19 CDS 0.55294120
## 140   reverse    360   rpl20 CDS 0.54117650
## 141   reverse    334  ssra tmRNA 0.52941179
## 142   reverse    318   rpl21 CDS 0.51764709
## 143   reverse    312   ycf66 CDS 0.50588238
## 144   reverse    303   rps14 CDS 0.49411765
## 145   reverse    255    psbE CDS 0.48235294
## 146   reverse    252   rpl27 CDS 0.47058824
## 147   reverse    249    atpH CDS 0.45882353
## 148   reverse    246    psaC CDS 0.44705883
## 149   reverse    219   rps18 CDS 0.43529412
## 150   reverse    213    thiS CDS 0.42352942
## 151   reverse    201    psbH CDS 0.41176471
## 152   reverse    198    psaE CDS 0.40000001
## 153   reverse    195   rpl35 CDS 0.38823530
## 154   reverse    195   ycf33 CDS 0.38823530
## 155   reverse    195   rpl33 CDS 0.38823530
## 156   reverse    186    psbZ CDS 0.35294119
## 157   reverse    165   rpl32 CDS 0.34117648
## 158   reverse    147   rpl34 CDS 0.32941177
## 159   reverse    135    psbK CDS 0.31764707
## 160   reverse    132    psbF CDS 0.30588236
## 161   reverse    126   rrn5 rRNA 0.29411766
## 162   reverse    120    psbJ CDS 0.28235295
## 163   reverse    117    psbX CDS 0.27058825
## 164   reverse    117    psbL CDS 0.27058825
## 165   reverse    114    petG CDS 0.24705882
## 166   reverse    111    psbY CDS 0.23529412
## 167   reverse    105   ycf12 CDS 0.22352941
## 168   reverse     99    psbT CDS 0.21176471
## 169   reverse     96    petL CDS 0.20000000
## 170   reverse     93    psaM CDS 0.18823530
## 171   reverse     87 trnL-2 tRNA 0.17647059
## 172   reverse     85 trnM-2 tRNA 0.16470589
## 173   reverse     82 trnL-1 tRNA 0.15294118
## 174   reverse     75  flrn ncRNA 0.14117648
## 175   reverse     74   trnI tRNA 0.12941177
## 176   reverse     74   trnP tRNA 0.12941177
## 177   reverse     73   trnE tRNA 0.10588235
## 178   reverse     73   trnW tRNA 0.10588235
## 179   reverse     73   trnF tRNA 0.10588235
## 180   reverse     73 trnR-1 tRNA 0.10588235
## 181   reverse     73   trnA tRNA 0.10588235
## 182   reverse     72 trnG-2 tRNA 0.04705882
## 183   reverse     72   trnC tRNA 0.04705882
## 184   reverse     71   trnC tRNA 0.02352941
## 185   reverse     71 trnG-1 tRNA 0.02352941
</code></pre>

<hr/>

<p><strong>Tableau</strong> </p>

<p><strong>Rank Table</strong>
In this table, we created a new column rank, partition the data by direction, and order by length in descending order. We generated exactly the same table as in R. In addition, we added the rank filter, where the user can select any range of rank they would like to see.</p>

<hr/>

<p><strong>Difference</strong> 
In the Difference table, we partitioned the data by direction, order by the length of gene in descending order. We generated two new columns MaxLen and Difference Len, showing the difference between the maximum gene length in each category with individual gene.</p>

<hr/>

<p><strong>Nth</strong> 
In the Nth table, we partioned the data by direction, order by the length of gene in descending order. We generated one new column showing the length of the gene in certain rank. We created a parameter Nth, the user can change the Nth from 1 to 5 to see the nth maximum gene length in each direction category.</p>

<hr/>

<p><strong>Cume_dist</strong> 
In the Cume_dist table, we caculated the cumulative distribution of gene length in each direction category. And in teh cumeFig, we visualized the distribution of gene length in different direction category. Different genes category are indicated by different color, and the cumulative sum is also represented by the size of the bar.</p>

</body>

</html>

